config/routes.rb
Rails.application.routes.draw do

  resource :components, only: [:index]

  root 'welcome#index'
  get '/about', to: 'welcome#about', as: 'about'
  get '/contact', to: 'welcome#contact', as: 'contact'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/components_controller.rb
class ComponentsController < ApplicationController
  def index
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @hello = 'Hello'
  end

  def about
    @hello = 'Hello'
  end

  def contact
    @hello = 'Hello'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include FrontEndModules::Cards
end

app/views/icons/_cross.html.erb
<svg class="<%= classes %>" viewBox="0 0 50 50">
  <title>Cross</title>
  <polygon points="20.4880066 24.8526861 10.9126022 34.4280904 15.1552429 38.6707311 24.7306472 29.0953268 34.3060516 38.6707311 38.5486923 34.4280904 28.9732879 24.8526861 38.5486923 15.2772818 34.3060516 11.0346411 24.7306472 20.6100454 15.1552429 11.0346411 10.9126022 15.2772818 20.4880066 24.8526861"></polygon>
</svg>

app/views/icons/_loader.html.erb
<svg class="<%= classes %>" viewBox="0 0 50 50">
  <title>loader</title>
  <path style="opacity: 0.5;" d="M25,43 C15.0588745,43 7,34.9411255 7,25 C7,15.0588745 15.0588745,7 25,7 C34.9411255,7 43,15.0588745 43,25 C43,34.9411255 34.9411255,43 25,43 Z M25,38 C32.1797017,38 38,32.1797017 38,25 C38,17.8202983 32.1797017,12 25,12 C17.8202983,12 12,17.8202983 12,25 C12,32.1797017 17.8202983,38 25,38 Z"></path>
  <path d="M25,43 C15.0588745,43 7,34.9411255 7,25 L12,25 C12,32.1797017 17.8202983,38 25,38 L25,43 L25,43 Z"></path>
</svg>

app/views/icons/_message.html.erb
<svg class="<%= classes %>" viewBox="0 0 50 50">
  <title>message</title>

  <path d="M13,8 L37,8 C37.5522847,8 38,8.44771525 38,9 L38,41 L38,41 C38,41.5522847 37.5522847,42 37,42 L13,42 C12.4477153,42 12,41.5522847 12,41 L12,9 L12,9 C12,8.44771525 12.4477153,8 13,8 L13,8 Z M16,17 C15.4477153,17 15,17.4477153 15,18 C15,18.5522847 15.4477153,19 16,19 L34,19 C34.5522847,19 35,18.5522847 35,18 C35,17.4477153 34.5522847,17 34,17 L16,17 Z M16,11 C15.4477153,11 15,11.4477153 15,12 C15,12.5522847 15.4477153,13 16,13 L22,13 C22.5522847,13 23,12.5522847 23,12 C23,11.4477153 22.5522847,11 22,11 L16,11 Z M16,21 C15.4477153,21 15,21.4477153 15,22 C15,22.5522847 15.4477153,23 16,23 L32,23 C32.5522847,23 33,22.5522847 33,22 C33,21.4477153 32.5522847,21 32,21 L16,21 Z M16,25 C15.4477153,25 15,25.4477153 15,26 C15,26.5522847 15.4477153,27 16,27 L34,27 C34.5522847,27 35,26.5522847 35,26 C35,25.4477153 34.5522847,25 34,25 L16,25 Z M16,29 L16,29 C15.4477153,29 15,29.4477153 15,30 C15,30.5522847 15.4477153,31 16,31 L29,31 C29.5522847,31 30,30.5522847 30,30 C30,29.4477153 29.5522847,29 29,29 L29,29 L16,29 Z M26,37 C25.4477153,37 25,37.4477153 25,38 C25,38.5522847 25.4477153,39 26,39 L34,39 C34.5522847,39 35,38.5522847 35,38 C35,37.4477153 34.5522847,37 34,37 L26,37 Z"></path>
</svg>

app/views/icons/_plus.html.erb
<svg class="<%= classes %>" viewBox="0 0 50 50">
  <title>plus</title>

  <path d="M28.3333333,21.6666667 L28.3333333,10 L21.6666667,10 L21.6666667,21.6666667 L10,21.6666667 L10,28.3333333 L21.6666667,28.3333333 L21.6666667,40 L28.3333333,40 L28.3333333,28.3333333 L40,28.3333333 L40,21.6666667 L28.3333333,21.6666667 Z"></path>
</svg>

app/views/icons/_select.html.erb
<svg class="<%= classes %>" viewBox="0 0 50 50">
  <title>select</title>
  <path d="M25.1923882,34.3345238 L25.2426407,34.3847763 L39.3847763,20.2426407 L35.1421356,16 L25.1923882,25.9497475 L15.2426407,16 L11,20.2426407 L25.1421356,34.3847763 L25.1923882,34.3345238 Z"></path>
</svg>

app/views/icons/_tick.html.erb
<svg class="<%= classes %>" viewBox="0 0 50 50">
  <title>Tick</title>
  <polygon points="10.1213203 24.0786797 5.87867966 28.3213203 17.3598096 39.8024503 43.9877216 16.2469897 40.0122784 11.7530103 17.6116189 31.5689783"></polygon>
</svg>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Station | Start</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'shared/fonts' %>
</head>
<body>
  <%= render 'shared/navigation/main' %>

  <%= yield %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

</body>
</html>

app/views/pages/_messages.html.erb
<section class="u-bg--gray u-padding-y-50">
  <div class="container">
    <h1 class="o-text--title u-color--night">Messages</h1>

    <%= render 'components/message', {
      icon: 'message',
      style: ' v--success',
      message: 'This is a message to you, my darling...'
    } %>

    <%= render 'components/message', {
      icon: 'message',
      style: ' v--shade',
      message: 'I would just like to tell you...'
    } %>

</section>

app/views/shared/_avatars.html.erb
<section class="u-bg--gray u-padding-y-50">

  <div class="container">
    <h1 class="o-text--title u-color--night">Avatars</h1>
    <div class="row">
      <div class="col-xs-12">
        <div>
          <div class="o-avatar v--xl" style="background-image: url('<%= asset_url("larry_page.jpeg") %>');" ></div>
          <div class="o-avatar v--lg" style="background-image: url('<%= asset_url("larry_page.jpeg") %>');" ></div>
          <div class="o-avatar v--md" style="background-image: url('<%= asset_url("larry_page.jpeg") %>');" ></div>
          <div class="o-avatar" style="background-image: url('<%= asset_url("larry_page.jpeg") %>');" ></div>
          <div class="o-avatar v--sm" style="background-image: url('<%= asset_url("larry_page.jpeg") %>');" ></div>
        </div>

        <div>
          <div class="o-avatar v--xl" style="background-image: url('<%= asset_url("logo.png") %>');" ></div>
          <div class="o-avatar v--lg" style="background-image: url('<%= asset_url("logo.png") %>');" ></div>
          <div class="o-avatar v--md" style="background-image: url('<%= asset_url("logo.png") %>');" ></div>
          <div class="o-avatar" style="background-image: url('<%= asset_url("logo.png") %>');" ></div>
          <div class="o-avatar v--sm" style="background-image: url('<%= asset_url("logo.png") %>');" ></div>
        </div>

      </div>
    </div>
  </div>

</section>

app/views/shared/_buttons.html.erb
<section class="u-bg--gray u-padding-y-50">
  <div class="container">
    <h1 class="o-text--title u-color--night">Buttons</h1>
    <div class="u-clearfix">
      <button class="o-btn c-btn c-btn--left v-lightgray c-btn--night u-spacer--sm-r"> Night </button>
      <button class="o-btn c-btn c-btn--left v-lightgray c-btn--disabled u-spacer--sm-r"> Disabled </button>
      <button class="o-btn c-btn c-btn--left v-lightgray c-btn--action u-spacer--sm-r"> Action </button>
      <button class="o-btn c-btn c-btn--left v-lightgray c-btn--success u-spacer--sm-r"> Success </button>
      <button class="o-btn c-btn c-btn--left v-lightgray c-btn--warning u-spacer--sm-r"> Warning </button>
      <button class="o-btn c-btn c-btn--left v-lightgray c-btn--error u-spacer--sm-r"> Error </button>
    </div>

    <div class="u-clearfix">
      <button class="o-btn c-btn c-btn--left c-btn--night u-spacer--sm-r"> Night </button>
      <button class="o-btn c-btn c-btn--left c-btn--disabled u-spacer--sm-r"> Disabled </button>
      <button class="o-btn c-btn c-btn--left c-btn--action u-spacer--sm-r"> Action </button>
      <button class="o-btn c-btn c-btn--left c-btn--success u-spacer--sm-r"> Success </button>
      <button class="o-btn c-btn c-btn--left c-btn--warning u-spacer--sm-r"> Warning </button>
      <button class="o-btn c-btn c-btn--left c-btn--error u-spacer--sm-r"> Error </button>
    </div>

    <div class="u-clearfix">
      <button class="o-btn c-btn c-btn--left v-night c-btn--white u-spacer--sm-r"> White </button>
      <button class="o-btn c-btn c-btn--left v-night c-btn--disabled u-spacer--sm-r"> Disabled </button>
      <button class="o-btn c-btn c-btn--left v-night c-btn--action u-spacer--sm-r"> Action </button>
      <button class="o-btn c-btn c-btn--left v-night c-btn--success u-spacer--sm-r"> Success </button>
      <button class="o-btn c-btn c-btn--left v-night c-btn--warning u-spacer--sm-r"> Warning </button>
      <button class="o-btn c-btn c-btn--left v-night c-btn--error u-spacer--sm-r"> Error </button>
    </div>

    <div class="u-clearfix">
      <button class="o-btn c-btn c-btn--left v-night-115 c-btn--white u-spacer--sm-r"> White </button>
      <button class="o-btn c-btn c-btn--left v-night-115 c-btn--disabled u-spacer--sm-r"> Disabled </button>
      <button class="o-btn c-btn c-btn--left v-night-115 c-btn--action u-spacer--sm-r"> Action </button>
      <button class="o-btn c-btn c-btn--left v-night-115 c-btn--success u-spacer--sm-r"> Success </button>
      <button class="o-btn c-btn c-btn--left v-night-115 c-btn--warning u-spacer--sm-r"> Warning </button>
      <button class="o-btn c-btn c-btn--left v-night-115 c-btn--error u-spacer--sm-r"> Error </button>
    </div>

    <div class="u-clearfix">
      <button class="o-btn c-btn c-btn--left v-full c-btn--white u-spacer--sm-r"> White </button>
      <button class="o-btn c-btn c-btn--left v-full c-btn--disabled u-spacer--sm-r"> Disabled </button>
      <button class="o-btn c-btn c-btn--left v-full c-btn--action u-spacer--sm-r"> Action </button>
      <button class="o-btn c-btn c-btn--left v-full c-btn--success u-spacer--sm-r"> Success </button>
      <button class="o-btn c-btn c-btn--left v-full c-btn--warning u-spacer--sm-r"> Warning </button>
      <button class="o-btn c-btn c-btn--left v-full c-btn--error u-spacer--sm-r"> Error </button>
    </div>

    <div class="u-clearfix">
      <button class="o-btn o-btn__icon c-btn c-btn--left v-full c-btn--white u-spacer--sm-r">
        <%= render 'icons/cross', classes: 'o-icon o-icon--inline' %>
        White
      </button>
      <button class="o-btn o-btn__icon c-btn c-btn--left v-full c-btn--disabled u-spacer--sm-r">
        <%= render 'icons/cross', classes: 'o-icon o-icon--inline' %>
        Disabled
      </button>
      <button class="o-btn o-btn__icon c-btn c-btn--left v-full c-btn--action u-spacer--sm-r">
        <%= render 'icons/loader', classes: 'o-icon o-icon--inline o-loader' %>
        Action
      </button>
      <button class="o-btn o-btn__icon c-btn c-btn--left v-full c-btn--success u-spacer--sm-r">
        <%= render 'icons/plus', classes: 'o-icon o-icon--inline' %>
        Success
      </button>
      <button class="o-btn o-btn__icon c-btn c-btn--left v-full c-btn--warning u-spacer--sm-r">
        <%= render 'icons/tick', classes: 'o-icon o-icon--inline' %>
        Warning
      </button>
      <button class="o-btn o-btn__icon c-btn c-btn--left v-full c-btn--error u-spacer--sm-r">
        <%= render 'icons/cross', classes: 'o-icon o-icon--inline' %>
        Error
      </button>
    </div>
  </div>
</section>

app/views/shared/_fonts.html.erb
<script src="https://use.typekit.net/ptb3pdu.js"></script>
<script>try{Typekit.load({ async: true });}catch(e){}</script>

app/views/shared/_forms.html.erb
<section class="u-bg--error u-padding-y-50">

  <div class="container">
    <div class="row">
      <div class="col-xs-12 offset-md-2 col-md-4">
        <h1 class="o-text--title u-color--white">Create a person</h1>
        <p class="o-text--body u-color--gray">
          This is body text for that form where we describe why on earth you would give information to anyone on the internet anymore.
        </p>
      </div>
      <div class="col-xs-12 col-md-4">
        <%= card(variant: 'error-115') do %>
          <h2 class="o-text--subtitle u-color--white">Create a person</h2>
          <div>
            <div class="o-tag v--error-130">Important</div>
            <div class="o-tag v--error-130">Secure</div>
          </div>
          <%= card(variant: 'white') do %>
            <div class="o-label__wrapper">
              <label for="1" class="o-label u-color--shade">First Name</label>
              <abbr class="o-label o-label o-label--right u-color--silver">*Required</abbr>
            </div>
            <input id="1" class="o-input" />
            <div class="o-label__wrapper">
              <label for="2" class="o-label u-color--shade">Last Name</label>
              <abbr class="o-label o-label o-label--right u-color--silver">*Required</abbr>
            </div>
            <input id="2" class="o-input" />
            <div class="o-label__wrapper">
              <label for="4" class="o-label u-color--shade">Nationality</label>
              <abbr class="o-label o-label o-label--right u-color--silver">*Required</abbr>
            </div>
            <div class="o-input-select__wrapper">
              <%= render 'icons/select', classes: 'o-icon o-input-select__icon' %>
              <select id="4" class="o-input o-input-select">
                <option>Argentina</option>
                <option>England</option>
                <option>France</option>
                <option>Holland</option>
              </select>
            </div>
            <div class="o-label__wrapper">
              <label for="3" class="o-label u-color--shade">Are you married?</label>
              <abbr class="o-label o-label o-label--right u-color--silver">*Required</abbr>
            </div>
            <div class="o-checkbox__wrapper">
              <input type="checkbox" id="3" class="o-checkbox__input"/>
              <div class="o-checkbox__icon-wrapper when-checked">
                <svg class="o-checkbox__icon" viewBox="0 0 50 50">
                  <title>Tick</title>
                  <polygon points="10.1213203 24.0786797 5.87867966 28.3213203 17.3598096 39.8024503 43.9877216 16.2469897 40.0122784 11.7530103 17.6116189 31.5689783"></polygon>
                </svg>
              </div>
              <label for="3" class="o-checkbox__label u-color when-checked">Yes I am married</label>

              <div class="o-checkbox__icon-wrapper when-unchecked">
                <svg class="o-checkbox__icon" viewBox="0 0 50 50">
                  <title>Cross</title>
                  <polygon points="20.4880066 24.8526861 10.9126022 34.4280904 15.1552429 38.6707311 24.7306472 29.0953268 34.3060516 38.6707311 38.5486923 34.4280904 28.9732879 24.8526861 38.5486923 15.2772818 34.3060516 11.0346411 24.7306472 20.6100454 15.1552429 11.0346411 10.9126022 15.2772818 20.4880066 24.8526861"></polygon>
                </svg>
              </div>
              <label for="3" class="o-checkbox__label u-color when-unchecked">No I am not married</label>

            </div>
            <div class="u-clearfix">
              <button class="o-btn c-btn c-btn--right c-btn--success v-full"> Create Person </button>
              <button class="o-btn c-btn c-btn--left c-btn--error v-lightgray"> Cancel </button>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

</section>

app/views/shared/_palette.html.erb
<section class="u-bg--lightgray u-padding-y-50">
  <div class="container">

    <h1 class="o-text--title u-color--night">Brand Colours</h1>

    <div class="row">
      <div class="col-sm-4">
        <%= card(variant: 'primary') do %>
          <p class="u-color--white">Primary</p>
          <div class="o-box u-bg--primary-115">
            <p class="u-color--white u-margin-0">115</p>
          </div>
          <div class="o-box u-bg--primary-130">
            <p class="u-color--white u-margin-0">130</p>
          </div>
        <% end %>
      </div>

      <div class="col-sm-4">
        <%= card(variant: 'secondary') do %>
          <p class="u-color--white">Secondary</p>
          <div class="o-box u-bg--secondary-115">
            <p class="u-color--white u-margin-0">115</p>
          </div>
          <div class="o-box u-bg--secondary-130">
            <p class="u-color--white u-margin-0">130</p>
          </div>
        <% end %>
      </div>

    </div>

    <h1 class="o-text--title u-color--night">Greyscale Colours</h1>

    <div class="row">

      <div class="col-sm-4">
        <%= card(variant: 'night') do %>
          <p class="u-color--white">Night</p>
          <div class="o-box u-bg--night-115">
            <p class="u-color--white u-margin-0">115</p>
          </div>
          <div class="o-box u-bg--night-130">
            <p class="u-color--white u-margin-0">130</p>
          </div>
        <% end %>
      </div>

      <div class="col-sm-4">
        <%= card(variant: 'shade') do %>
          <p class="u-color--white">Shade</p>
          <div class="o-box u-bg--shade-115">
            <p class="u-color--white u-margin-0">115</p>
          </div>
          <div class="o-box u-bg--shade-130">
            <p class="u-color--white u-margin-0">130</p>
          </div>
        <% end %>
      </div>

      <div class="col-sm-4">
        <%= card(variant: 'silver') do %>
          <p class="u-color--white">Silver</p>
          <div class="o-box u-bg--silver-115">
            <p class="u-color--white u-margin-0">115</p>
          </div>
          <div class="o-box u-bg--silver-130">
            <p class="u-color--white u-margin-0">130</p>
          </div>
        <% end %>
      </div>

    </div>

    <div class="row">

      <div class="col-sm-4">
        <%= card(variant: 'gray') do %>
          <p class="u-color--night">Gray</p>
          <div class="o-box u-bg--gray-115">
            <p class="u-color--night u-margin-0">115</p>
          </div>
          <div class="o-box u-bg--gray-130">
            <p class="u-color--night u-margin-0">130</p>
          </div>
        <% end %>
      </div>

      <div class="col-sm-4">
        <%= card(variant: 'lightgray') do %>
          <p class="u-color--night">Light Gray</p>
        <% end %>
      </div>

      <div class="col-sm-4">
        <%= card(variant: 'white') do %>
          <p class="u-color--night">White</p>
        <% end %>
      </div>

    </div>

    <h1 class="o-text--title u-color--night">Utility Colours</h1>

    <div class="row">

      <div class="col-sm-4">
        <%= card(variant: 'error') do %>
          <p class="u-color--white">Error</p>
          <div class="o-box u-bg--error-115">
            <p class="u-color--white u-margin-0">115</p>
          </div>
          <div class="o-box u-bg--error-130">
            <p class="u-color--white u-margin-0">130</p>
          </div>
        <% end %>
      </div>

      <div class="col-sm-4">
        <%= card(variant: 'warning') do %>
          <p class="u-color--white">Warning</p>
          <div class="o-box u-bg--warning-115">
            <p class="u-color--white u-margin-0">115</p>
          </div>
          <div class="o-box u-bg--warning-130">
            <p class="u-color--white u-margin-0">130</p>
          </div>
        <% end %>
      </div>

      <div class="col-sm-4">
        <%= card(variant: 'success') do %>
          <p class="u-color--white">Success</p>
          <div class="o-box u-bg--success-115">
            <p class="u-color--white u-margin-0">115</p>
          </div>
          <div class="o-box u-bg--success-130">
            <p class="u-color--white u-margin-0">130</p>
          </div>
        <% end %>
      </div>

    </div>

  </div>
</section>

app/views/shared/_tags.html.erb
<section class="u-bg--white u-padding-y-50">

  <div class="container">
    <div class="row">
      <div class="col-xs-4">
        <h1 class="o-text--title u-color--night">
          Tags
        </h1>
        <%= card(variant: 'white') do %>
          <div class="o-tag v--primary">Primary</div>
          <div class="o-tag v--secondary">Secondary</div>
          <div class="o-tag v--warning">Secondary</div>
          <div class="o-tag v--error">Secondary</div>
          <div class="o-tag v--night">Secondary</div>
          <div class="o-tag v--shade">Secondary</div>
          <div class="o-tag v--silver">Secondary</div>
          <div class="o-tag v--gray">Secondary</div>
          <div class="o-tag v--lightgray">Secondary</div>
          <div class="o-tag v--white">Secondary</div>
        <% end %>

        <%= card(variant: 'white') do %>
          <div class="o-tag v--border v--primary">Primary</div>
          <div class="o-tag v--border v--secondary">Secondary</div>
          <div class="o-tag v--border v--warning">Warning</div>
          <div class="o-tag v--border v--error">Error</div>
          <div class="o-tag v--border v--night">Night</div>
          <div class="o-tag v--border v--shade">Shade</div>
          <div class="o-tag v--border v--silver">Silver</div>
          <div class="o-tag v--border v--gray">Gray</div>
          <div class="o-tag v--border v--lightgray">Lightgray</div>
          <div class="o-tag v--border v--white">White</div>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/shared/_typography.html.erb
<section class="u-bg--lightgray u-padding-y-50">
  <div class="container">
    <h1 class="o-text--heading u-color--night">Typography</h1>

    <h1 class="o-text--heading u-color--shade">This is a Heading</h1>
    <h2 class="o-text--subheading u-color--shade">This is a Subheading</h2>
    <h3 class="o-text--title u-color--shade">This is a Title</h3>
    <h4 class="o-text--subtitle u-color--shade">This is a Subtitle</h4>
    <p class="o-text--body u-color--shade">This is a Body</p>
    <label class="o-text--label u-color--shade">This is a Label</label>

  </div>
</section>

app/views/shared/navigation/_main.html.erb
<section class="container">
  <nav class="c-navigation">
    <ul class="c-navigation__list">
      <%= link_to root_path do %>
        <li class="c-navigation__item u-bg--night-115 v--success">
          <%= render 'icons/tick', classes: 'o-icon o-icon--inline-flex' %>
          Intention
        </li>
      <% end %>
      <%= link_to about_path do %>
        <li class="c-navigation__item u-bg--night-115 v--action">
          <%= render 'icons/loader', classes: 'o-icon o-icon--inline-flex o-loader' %>
          About
        </li>
      <% end %>
      <%= link_to contact_path do %>
        <li class="c-navigation__item u-bg--night-115 v--warning">
          <%= render 'icons/message', classes: 'o-icon o-icon--inline-flex' %>
          Contact
        </li>
      <% end %>
    </ul>
  </nav>
</section>

app/views/welcome/about.html.erb
<section class="u-bg--secondary u-padding-y-50">
  <div class="container">
    <h1 class="o-text o-text--heading u-color--night">About</h1>

    <%= card(variant: 'secondary-115') do %>
      <h2 class="o-text o-text--title u-color--night u-margin-0">Something about something</h2>
    <% end %>
  </div>
</section>

app/views/welcome/contact.html.erb
<section class="u-bg--warning u-padding-y-50">
  <div class="container">
    <h1 class="o-text o-text--heading u-color--night">Contact</h1>

    <%= card(variant: 'warning-115') do %>
      <h2 class="o-text o-text--title u-color--night u-margin-0">Contacting something or another</h2>
    <% end %>
  </div>
</section>

app/views/welcome/index.html.erb
<section class="u-bg--night u-padding-y-50">
  <div class="container">
    <h1 class="o-text o-text--heading u-color--primary">Station</h1>

    <%= card(variant: 'night-115') do %>
      <h2 class="o-text o-text--title u-color--white u-margin-0">Where we arrive @ good design</h2>
    <% end %>
  </div>
</section>

<%= render 'shared/palette' %>
<%= render 'shared/typography' %>
<%= render 'shared/buttons' %>
<%= render 'shared/avatars' %>
<%= render 'shared/tags' %>
<%= render 'shared/forms' %>
<%= render 'pages/messages' %>